config:
  bootstrap:
    tenant_subdomain: ${britive.broker.tenant.subdomain}  # required
    authentication_token_generator: ${britive.broker.authentication.token.script}  # one of authentication_token or authentication_token_generator is required
  http_proxy:  # optional, if not specified do not use http proxy for connecting
    host: localhost      # required
    port: 8080           # required
    username: userA      # optional: if this or password not specified authorization type is None
    password: passwordA  # optional: if this or username not specified authorization type is None
    connection_type: [Legacy | Forwarding | Tunneling]   # optional defaults to Tunneling if not specified

