#!/usr/bin/env bash
# ============================================================
# Lab Setup — HashiCorp Vault (local Docker dev server)
# ============================================================
# Starts a Vault dev server via Docker Compose, then:
#   - Enables KV v2 at the 'secret/' mount
#   - Creates a least-privilege policy
#   - Creates a scoped Vault token with that policy
#   - Creates an AppRole role + secret ID (for AppRole tests)
#   - Writes an initial placeholder secret
#
# Writes all connection details to .env for test-sync.sh and
# teardown.sh.
#
# Prerequisites:
#   - Docker (with Compose v2 plugin or docker-compose v1)
#   - Vault CLI installed (for provisioning after startup)
#   - jq installed
#
# To use HCP Vault Dedicated instead of Docker, skip this
# script and populate .env manually — see README.md.
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*"; }
err() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] ERROR: $*" >&2; }
die() { err "$*"; exit 1; }

# ── Defaults ─────────────────────────────────────────────────
VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
ROOT_TOKEN="britive-lab-root-token"
KV_MOUNT="secret"
SECRET_PATH="${KV_MOUNT}/britive-lab/test"
SECRET_KEY="password"
POLICY_NAME="britive-lab-policy"
TOKEN_NAME="britive-lab-token"
APPROLE_NAME="britive-lab-approle"

# ── Checks ───────────────────────────────────────────────────
command -v vault  &>/dev/null || die "Vault CLI is not installed (https://developer.hashicorp.com/vault/downloads)."
command -v jq     &>/dev/null || die "jq is not installed."

# Detect Compose command
if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
else
    die "Docker Compose (v1 or v2 plugin) is not installed."
fi

# ── Start Vault container ─────────────────────────────────────
log "Starting Vault dev container..."
${COMPOSE_CMD} -f "${SCRIPT_DIR}/docker-compose.yml" up -d

log "Waiting for Vault to be ready..."
export VAULT_ADDR
export VAULT_TOKEN="${ROOT_TOKEN}"

for i in $(seq 1 24); do
    vault status -address="${VAULT_ADDR}" &>/dev/null && break
    [[ ${i} -eq 24 ]] && die "Vault did not become ready within 120 s."
    sleep 5
done
log "Vault is ready at ${VAULT_ADDR}"

# ── Enable KV v2 (already enabled in dev mode, tune it) ──────
# KV v2 is enabled by default at 'secret/' in dev mode.
# Ensure it's definitely v2.
if vault secrets list -format=json | jq -e '."secret/"' &>/dev/null; then
    log "KV mount 'secret/' already enabled — skipping."
else
    log "Enabling KV v2 at 'secret/'..."
    vault secrets enable -path="${KV_MOUNT}" kv-v2
fi

# ── Policy ───────────────────────────────────────────────────
log "Creating policy '${POLICY_NAME}'..."
vault policy write "${POLICY_NAME}" - <<'POLICY'
# Britive lab: write + read a specific secret path only
path "secret/data/britive-lab/*" {
  capabilities = ["create", "update", "read"]
}
path "secret/metadata/britive-lab/*" {
  capabilities = ["read", "list"]
}
POLICY

# ── Scoped token ─────────────────────────────────────────────
log "Creating scoped token '${TOKEN_NAME}'..."
TOKEN_JSON=$(vault token create \
    -display-name "${TOKEN_NAME}" \
    -policy       "${POLICY_NAME}" \
    -ttl          "24h" \
    -format       json)
VAULT_TOKEN_LAB=$(echo "${TOKEN_JSON}" | jq -r '.auth.client_token')

# ── AppRole ───────────────────────────────────────────────────
log "Enabling AppRole auth method..."
vault auth enable approle 2>/dev/null || log "AppRole already enabled."

log "Creating AppRole role '${APPROLE_NAME}'..."
vault write "auth/approle/role/${APPROLE_NAME}" \
    "policies=${POLICY_NAME}" \
    "token_ttl=1h" \
    "token_max_ttl=4h" \
    "secret_id_ttl=24h" \
    "secret_id_num_uses=0"

APPROLE_ROLE_ID=$(vault read -field=role_id "auth/approle/role/${APPROLE_NAME}/role-id")
APPROLE_SECRET_ID=$(vault write -force -field=secret_id "auth/approle/role/${APPROLE_NAME}/secret-id")

# ── Initial secret ────────────────────────────────────────────
log "Creating initial placeholder secret..."
vault kv put "${SECRET_PATH}" "${SECRET_KEY}=initial-placeholder" >/dev/null

# ── Write .env ───────────────────────────────────────────────
log "Writing connection details to ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Britive Lab — HashiCorp Vault (Docker dev server)
# Generated by setup.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# DO NOT COMMIT THIS FILE

# Vault address
VAULT_ADDR=${VAULT_ADDR}

# Scoped token (used by CLI and token-auth curl variant)
VAULT_TOKEN=${VAULT_TOKEN_LAB}

# AppRole credentials (used by AppRole curl variant)
VAULT_ROLE_ID=${APPROLE_ROLE_ID}
VAULT_SECRET_ID_AR=${APPROLE_SECRET_ID}

# Target secret
VAULT_SECRET_PATH=${SECRET_PATH}
VAULT_SECRET_KEY=${SECRET_KEY}
VAULT_KV_VERSION=2

# Resource identifiers (used by teardown.sh)
LAB_ROOT_TOKEN=${ROOT_TOKEN}
LAB_APPROLE_NAME=${APPROLE_NAME}
LAB_POLICY_NAME=${POLICY_NAME}
EOF
chmod 600 "${ENV_FILE}"

log "Setup complete."
log ""
log "  Vault UI : ${VAULT_ADDR}/ui  (token: ${ROOT_TOKEN})"
log "  Secret   : ${SECRET_PATH}  key: ${SECRET_KEY}"
log ""
log "Next steps:"
log "  ./test-sync.sh    — run and verify all script variants"
log "  ./teardown.sh     — stop container and clean up when done"
