#!/usr/bin/env bash
# ============================================================
# Lab Setup — AWS Secrets Manager
# ============================================================
# Creates the minimum AWS resources needed to test the sync
# scripts:
#   - IAM policy with least-privilege SecretsManager access
#   - IAM user with that policy attached
#   - IAM access key for the user
#   - A Secrets Manager secret with an initial placeholder value
#
# Writes credentials + resource names to .env for use by
# test-sync.sh and teardown.sh.
#
# Prerequisites:
#   - AWS CLI v2 installed and authenticated (admin rights to
#     create IAM resources and Secrets Manager secrets)
#   - jq installed
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

log()  { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*"; }
err()  { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] ERROR: $*" >&2; }
die()  { err "$*"; exit 1; }

# ── Defaults (override via env vars before running) ──────────
AWS_REGION="${AWS_REGION:-us-east-1}"
SECRET_NAME="${SECRET_NAME:-britive-lab/test-secret}"
IAM_USER="${IAM_USER:-britive-lab-user}"
IAM_POLICY_NAME="${IAM_POLICY_NAME:-britive-lab-policy}"

# ── Checks ───────────────────────────────────────────────────
command -v aws  &>/dev/null || die "AWS CLI is not installed."
command -v jq   &>/dev/null || die "jq is not installed."

log "Getting current AWS account ID..."
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
log "Account: ${ACCOUNT_ID}  Region: ${AWS_REGION}"

SECRET_ARN="arn:aws:secretsmanager:${AWS_REGION}:${ACCOUNT_ID}:secret:${SECRET_NAME}"

# ── IAM policy ───────────────────────────────────────────────
POLICY_ARN="arn:aws:iam::${ACCOUNT_ID}:policy/${IAM_POLICY_NAME}"

if aws iam get-policy --policy-arn "${POLICY_ARN}" &>/dev/null; then
    log "IAM policy '${IAM_POLICY_NAME}' already exists — skipping."
else
    log "Creating IAM policy '${IAM_POLICY_NAME}'..."
    POLICY_DOC=$(jq -n \
        --arg arn "${SECRET_ARN}*" \
        '{
            "Version": "2012-10-17",
            "Statement": [{
                "Sid": "BritiveLab",
                "Effect": "Allow",
                "Action": [
                    "secretsmanager:PutSecretValue",
                    "secretsmanager:GetSecretValue",
                    "secretsmanager:DescribeSecret"
                ],
                "Resource": $arn
            }]
        }')
    POLICY_ARN=$(aws iam create-policy \
        --policy-name "${IAM_POLICY_NAME}" \
        --description  "Britive lab: scoped SecretsManager access" \
        --policy-document "${POLICY_DOC}" \
        --query 'Policy.Arn' --output text)
    log "Policy created: ${POLICY_ARN}"
fi

# ── IAM user ─────────────────────────────────────────────────
if aws iam get-user --user-name "${IAM_USER}" &>/dev/null; then
    log "IAM user '${IAM_USER}' already exists — skipping."
else
    log "Creating IAM user '${IAM_USER}'..."
    aws iam create-user --user-name "${IAM_USER}" >/dev/null
fi

log "Attaching policy to user..."
aws iam attach-user-policy \
    --user-name "${IAM_USER}" \
    --policy-arn "${POLICY_ARN}" 2>/dev/null || true

# ── Access key ───────────────────────────────────────────────
# Delete any existing keys first (IAM allows max 2; keep things clean)
EXISTING_KEYS=$(aws iam list-access-keys \
    --user-name "${IAM_USER}" \
    --query 'AccessKeyMetadata[].AccessKeyId' --output text)
for KEY_ID in ${EXISTING_KEYS}; do
    log "Deleting existing access key ${KEY_ID}..."
    aws iam delete-access-key --user-name "${IAM_USER}" --access-key-id "${KEY_ID}"
done

log "Creating access key for '${IAM_USER}'..."
KEY_JSON=$(aws iam create-access-key --user-name "${IAM_USER}")
ACCESS_KEY_ID=$(echo "${KEY_JSON}"     | jq -r '.AccessKey.AccessKeyId')
SECRET_ACCESS_KEY=$(echo "${KEY_JSON}" | jq -r '.AccessKey.SecretAccessKey')

# ── Secrets Manager secret ───────────────────────────────────
if aws secretsmanager describe-secret \
        --secret-id "${SECRET_NAME}" \
        --region    "${AWS_REGION}" &>/dev/null; then
    log "Secret '${SECRET_NAME}' already exists — skipping."
else
    log "Creating Secrets Manager secret '${SECRET_NAME}'..."
    aws secretsmanager create-secret \
        --name        "${SECRET_NAME}" \
        --description "Britive lab test secret" \
        --secret-string "initial-placeholder" \
        --region "${AWS_REGION}" \
        >/dev/null
fi

# ── Write .env ───────────────────────────────────────────────
log "Writing credentials to ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Britive Lab — AWS Secrets Manager
# Generated by setup.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# DO NOT COMMIT THIS FILE

# Credentials for the test IAM user
AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}

# Target secret
AWS_SECRET_NAME=${SECRET_NAME}

# Resource identifiers (used by teardown.sh)
LAB_IAM_USER=${IAM_USER}
LAB_IAM_POLICY_ARN=${POLICY_ARN}
EOF
chmod 600 "${ENV_FILE}"

log "Setup complete."
log ""
log "  Region : ${AWS_REGION}"
log "  Secret : ${SECRET_NAME}"
log "  IAM user: ${IAM_USER}"
log ""
log "Next steps:"
log "  ./test-sync.sh    — run and verify all script variants"
log "  ./teardown.sh     — delete all lab resources when done"
