#!/usr/bin/env bash
# ============================================================
# Lab Setup — GCP Secret Manager
# ============================================================
# Creates the minimum GCP resources needed to test the sync
# scripts:
#   - Enables the Secret Manager API
#   - Creates a service account with scoped IAM binding
#   - Creates a SA key file (sa-key.json)
#   - Creates the target secret with an initial placeholder version
#
# Writes credentials + resource names to .env for use by
# test-sync.sh and teardown.sh.
#
# Prerequisites:
#   - gcloud CLI installed and authenticated
#     (needs resourcemanager.projects.setIamPolicy or
#      secretmanager.admin role on the project)
#   - jq installed
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
SA_KEY_FILE="${SCRIPT_DIR}/sa-key.json"

log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*"; }
err() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] ERROR: $*" >&2; }
die() { err "$*"; exit 1; }

# ── Defaults ─────────────────────────────────────────────────
GCP_PROJECT_ID="${GCP_PROJECT_ID:-$(gcloud config get-value project 2>/dev/null)}"
SECRET_NAME="${SECRET_NAME:-britive-lab-test-secret}"
SA_NAME="${SA_NAME:-britive-lab-sa}"
SA_DISPLAY_NAME="${SA_DISPLAY_NAME:-Britive Lab Service Account}"

# ── Checks ───────────────────────────────────────────────────
command -v gcloud &>/dev/null || die "gcloud CLI is not installed."
command -v jq     &>/dev/null || die "jq is not installed."

[[ -z "${GCP_PROJECT_ID}" ]] && die "GCP project not set. Run: gcloud config set project PROJECT_ID"
log "Project: ${GCP_PROJECT_ID}"

SA_EMAIL="${SA_NAME}@${GCP_PROJECT_ID}.iam.gserviceaccount.com"

# ── Enable Secret Manager API ────────────────────────────────
log "Enabling Secret Manager API..."
gcloud services enable secretmanager.googleapis.com \
    --project="${GCP_PROJECT_ID}" --quiet

# ── Service account ───────────────────────────────────────────
if gcloud iam service-accounts describe "${SA_EMAIL}" \
        --project="${GCP_PROJECT_ID}" &>/dev/null; then
    log "Service account '${SA_EMAIL}' already exists — skipping creation."
else
    log "Creating service account '${SA_NAME}'..."
    gcloud iam service-accounts create "${SA_NAME}" \
        --display-name="${SA_DISPLAY_NAME}" \
        --project="${GCP_PROJECT_ID}" --quiet
fi

# ── Secret ────────────────────────────────────────────────────
if gcloud secrets describe "${SECRET_NAME}" \
        --project="${GCP_PROJECT_ID}" &>/dev/null; then
    log "Secret '${SECRET_NAME}' already exists — skipping creation."
else
    log "Creating secret '${SECRET_NAME}'..."
    gcloud secrets create "${SECRET_NAME}" \
        --replication-policy="automatic" \
        --project="${GCP_PROJECT_ID}" --quiet

    log "Adding initial placeholder version..."
    printf 'initial-placeholder' | gcloud secrets versions add "${SECRET_NAME}" \
        --data-file=- \
        --project="${GCP_PROJECT_ID}" --quiet
fi

# ── IAM: grant SA access to this specific secret ─────────────
log "Granting 'roles/secretmanager.secretVersionAdder' + 'secretmanager.viewer' to SA..."
gcloud secrets add-iam-policy-binding "${SECRET_NAME}" \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="roles/secretmanager.secretVersionAdder" \
    --project="${GCP_PROJECT_ID}" \
    --quiet >/dev/null

gcloud secrets add-iam-policy-binding "${SECRET_NAME}" \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="roles/secretmanager.viewer" \
    --project="${GCP_PROJECT_ID}" \
    --quiet >/dev/null

# For the disable-previous-versions feature the SA also needs secretVersionManager
gcloud secrets add-iam-policy-binding "${SECRET_NAME}" \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="roles/secretmanager.secretVersionManager" \
    --project="${GCP_PROJECT_ID}" \
    --quiet >/dev/null

# ── SA key ────────────────────────────────────────────────────
log "Creating service account key..."
gcloud iam service-accounts keys create "${SA_KEY_FILE}" \
    --iam-account="${SA_EMAIL}" \
    --project="${GCP_PROJECT_ID}" --quiet
chmod 600 "${SA_KEY_FILE}"
log "Key written to ${SA_KEY_FILE}"

# ── Write .env ───────────────────────────────────────────────
log "Writing credentials to ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Britive Lab — GCP Secret Manager
# Generated by setup.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# DO NOT COMMIT THIS FILE

# GCP project and target secret
GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_SECRET_NAME=${SECRET_NAME}

# Service account key (used by gcloud CLI and curl variants)
GCP_SA_KEY_FILE=${SA_KEY_FILE}

# Resource identifiers (used by teardown.sh)
LAB_SA_EMAIL=${SA_EMAIL}
EOF
chmod 600 "${ENV_FILE}"

log "Setup complete."
log ""
log "  Project : ${GCP_PROJECT_ID}"
log "  Secret  : ${SECRET_NAME}"
log "  SA      : ${SA_EMAIL}"
log "  Key file: ${SA_KEY_FILE}"
log ""
log "Next steps:"
log "  ./test-sync.sh    — run and verify all script variants"
log "  ./teardown.sh     — delete all lab resources when done"
